id: IC4CA441C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T11:39:30+00:00'
last_modified: '2022-06-08T06:12:26.022593+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD17448
  title: མཚོ་སྔོན་མི་རིགས་སློབ་གྲྭ་ཆེན་མོའི་བོད་རིག་པའི་སློབ་གླིང་གི་དུས་རབས ༢༡པའི་ཞིབ་འཇུག་སློབ་མའི་ཕུལ་བྱུང་མཐར་ཕྱིན་དཔྱད་རྩོམ་བདམས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    A358:
      image_group_id: I2PD19793
      title: ''
      total_pages: 532
      order: 1
      base_file: A358.txt
    22A1:
      image_group_id: I2PD19794
      title: ''
      total_pages: 646
      order: 2
      base_file: 22A1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
