id: P006695
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W2PD17448
  title: མཚོ་སྔོན་མི་རིགས་སློབ་གྲྭ་ཆེན་མོའི་བོད་རིག་པའི་སློབ་གླིང་གི་དུས་རབས ༢༡པའི་ཞིབ་འཇུག་སློབ་མའི་ཕུལ་བྱུང་མཐར་ཕྱིན་དཔྱད་རྩོམ་བདམས་བསྒྲིགས།
  author: ''
  volumes:
    348d6c14e6af431da6e8ae6fb84c6d70:
      image_group_id: I2PD19793
      title: ''
      volume_number: 1
      total_pages: 532
      base_file: v001.txt
    2e9d2e0beb35476097c6e20482407068:
      image_group_id: I2PD19794
      title: ''
      volume_number: 2
      total_pages: 646
      base_file: v002.txt
